---
title: "Module 12"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Covariation}
library(ggplot2)
library(curl)
library(manipulate)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/zombies.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = FALSE)

w <- d$weight
h <- d$height
n <- length(w)  # or length(h)
cov_wh <- sum((w - mean(w)) * (h - mean(h)))/(n - 1)
cov_wh

cov(w, h) # built in function
```

```{r Correlation}
sd_w <- sd(w)
sd_h <- sd(h)
cor_wh <- cov_wh/(sd_w * sd_h)
cor_wh
cor(w, h) # built in function
cor(w, h, method = "pearson")
cor(w, h, method = "spearman")
cor(w, h, method = "kendall")
```

```{r Regression, eval=FALSE}
y <- h - mean(h)
x <- w - mean(w)
z <- data.frame(cbind(x, y))
slope.test <- function(beta1) {
    g <- ggplot(data = z, aes(x = x, y = y))
    g <- g + geom_point()
    g <- g + geom_abline(intercept = 0, slope = beta1, size = 1, colour = "blue",
        alpha = 1/2)
    ols <- sum((y - beta1 * x)^2)
    g <- g + ggtitle(paste("Slope = ", beta1, "\nSum of Squared Deviations = ",
        round(ols, 3)))
    g
}
manipulate(plot(1:5, cex = size), size = slider(0.5, 10, step = 0.5))  #priming the interface
manipulate(slope.test(beta1), beta1 = slider(-1, 1, initial = 0, step = 0.005))
beta1 <- cov(w, h)/var(w)
beta1
beta0 <- mean(h) - beta1 * mean(w)
beta0
m <- lm(data = d, height ~ weight)
summary(m)
```